blog_main/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import *
from django.conf.urls.static import static
from django.conf import settings
from blogs import views as BlogViews
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home,name='home'),
    path('category/',include('blogs.urls')),
    path('blogs/<slug:slug>/',BlogViews.blogs,name='blogs'),
    path('blog/search/',BlogViews.search,name='search'),
    path('register/',register,name='register'),
    path('login/',login,name='login'),
    path('logout/',logout,name='logout'),

    # dashboards urls
    path('dashboards/',include('dashboards.urls')),


    path('ckeditor/', include('ckeditor_uploader.urls')),
     path('ckeditor5/', include('django_ckeditor_5.urls')),
    

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blogs/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path('<int:category_id>/',post_by_category,name='post_by_category')
]

dashboards/urls.py
from django.urls import path
from .views import *
urlpatterns =[
    path('',dashboards,name='dashboards'),
    # Category
    path('categories/',categories,name='categories'),
    path('categories/add/',add_category,name='add_category'),
    path('categories/edit/<int:pk>/',edit_category,name='edit_category'),
    path('categories/delete/<int:pk>/',delete_category,name='delete_category'),

    # Blog Post Cards
    path('posts/',posts,name='posts'),
    path('posts/add/',add_post,name='add_post'),
    path('posts/edit/<int:pk>/',edit_post,name='edit_post'),
    path('posts/delete/<int:pk>/',delete_post,name='delete_post'),

    # Users

    path('users/',users,name='user'),
    path('users/add',add_user,name='add_user'),
    path('users/edit/<int:pk>/',edit_user,name='edit_user'),
    path('user/delete/<int:pk>/',delete_user,name='delete_user'),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User
from django_ckeditor_5.fields import CKEditor5Field
# Create your models here.

class Category(models.Model):
    category_name = models.CharField(max_length=200,unique=True)
    create_at = models.DateField(auto_now=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.category_name
    
STATUS_CHOICES = (
    ('Draft','Draft'),
    ('Published','Published')
)
class Blog(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=150,unique=True,blank=True)
    category =models.ForeignKey(Category,on_delete=models.CASCADE)
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    featured_image =models.ImageField(upload_to='uploads/%Y/%m/%d')
    short_description = CKEditor5Field('Short Description', config_name='default')
    blog_body = CKEditor5Field('Blog Body', config_name='default')
    status = models.CharField(choices=STATUS_CHOICES,default='Draft')
    is_featured = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    

class Comments(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog,on_delete=models.CASCADE)
    comment = models.TextField(max_length=250)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    
    class Meta:
        verbose_name_plural = 'Comments'

    def __str__(self):
        return self.comment
    

        

dashboards/models.py
from django.db import models

# Create your models here.

dashboards/forms.py
from django import forms
from blogs.models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'


class BlogPostForm(forms.ModelForm):
    class Meta:
        model = Blog
        exclude = ['slug','author']

class AddUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','is_active','is_staff','is_superuser','groups','user_permissions']

class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','is_active','is_staff','is_superuser','groups','user_permissions']

dashboards/views.py
from django.shortcuts import render,redirect,get_object_or_404
from blogs.models import *
from django.contrib.auth.decorators import login_required
from .forms import *
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.contrib import messages
from django.urls import reverse
# Create your views here.


@login_required(login_url='login')
def dashboards(request):
    category_count = Category.objects.all().count()
    blogs_count = Blog.objects.all().count()
    context = {
        'category_count':category_count,
        'blogs_count':blogs_count,
    }
    return render(request,'dashboards/dashboards.html',context)

def categories(request):
    return render(request,'dashboards/categories.html')

def add_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,"📂 New category added successfully.")
            return redirect('categories')
        else:
            messages.error(request,"❌ Failed to add category. Please check the form.")
            return redirect('categories')
    else:
        form = CategoryForm()
    context = {
        'form':form,
    }
    return render(request,'dashboards/add_category.html',context)
def edit_category(request,pk):
    category = get_object_or_404(Category,pk=pk)
    if request.method == 'POST':
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            messages.success(request, "✏️ Category updated successfully.")
            return redirect('categories')
        else:
            messages.error(request,"❌ Failed to update category. Please check the form.")
            return redirect('categories')
    else:
        form = CategoryForm(instance=category)
    
    context = {
        'form': form,
        'category':category
    }
    
    
    return render(request,'dashboards/edit_category.html',context)

def delete_category(request,pk):
    category = get_object_or_404(Category,pk=pk)
    if request.method == 'POST':
        category.delete()
        messages.warning(request,"🗑️ Category deleted successfully.")
        return redirect('categories')
    context ={
        'category':category,
        'cancel':reverse('categories')
    }
    return render(request,'dashboards/confirm_delete.html',context)

def posts(request):
    posts = Blog.objects.all()
    context = {
        'posts':posts,
    }
    return render(request,'dashboards/posts.html',context)

def add_post(request):
    if request.method == 'POST':
        form = BlogPostForm(request.POST,request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            title = form.cleaned_data['title']
            post.slug = slugify(title) + "-" + str(post.id)
            post.save()
            messages.success(request,"New Blog Post added successfully."
            )
            return redirect('posts')
        else:
            messages.error(request,"❌ Failed to add Blog Post. Please check the form.")
            return redirect('posts')
    form = BlogPostForm()
    context = {
        'form':form,
    }
    return render(request,'dashboards/add_post.html',context)

def edit_post(request,pk):
    post = get_object_or_404(Blog,pk=pk)
    # 🚫 Permission check AFTER click
    if post.author != request.user:
        messages.warning(
            request,
            "⛔ You don't have permission to edit this blog."
        )
        return redirect('posts')    
    if request.method == 'POST':
        form = BlogPostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            messages.success(request, "✏️ Blog Post updated successfully.")
            return redirect('posts')
        else:
            messages.error(request,"❌ Failed to update Blog Post. Please check the form.")
            return redirect('posts')

    else:
        form = BlogPostForm(instance=post)
    
    context = {
        'form': form,
        'post':post,
    }

    return render(request,'dashboards/edit_post.html',context)

def delete_post(request,pk):
    post = get_object_or_404(Blog,pk=pk)
    # 🚫 Permission check AFTER click
    if post.author != request.user:
        messages.warning(
            request,
            "⛔ You don't have permission to delete this blog."
        )
        return redirect('posts')
    if request.method == 'POST':
        post.delete()
        messages.warning(request,"🗑️ Blog Post deleted successfully.")
        return redirect('posts')
    context ={
        'post':post,
        'cancel':reverse('posts')
    }
    return render(request,'dashboards/confirm_delete.html',context)
    


def users(request):
    users = User.objects.all()
    context ={
        'users':users,
    }
    return render(request,'dashboards/users.html',context)

def add_user(request):
    if request.method == 'POST':
        form = AddUserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,"New Blog Post added successfully.")
            return redirect('user')
        else:
            messages.error(
                request,
                "❌ Failed to add user. Please correct the errors below."
            )
            return redirect('add_user')
    form = AddUserForm()
    context ={
        'form':form,
    }
    return render(request,'dashboards/add_user.html',context)

def edit_user(request,pk):
    user = get_object_or_404(User,pk=pk)
    if request.method == 'POST':
        form = EditUserForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            messages.success(request,"✏️ User details updated successfully.")
            return redirect('user')
    else:
        form = EditUserForm(instance=user)
    
    context = {
        'form': form,
        'user':user,
    }

    return render(request,'dashboards/edit_user.html',context)

def delete_user(request,pk):
    user = get_object_or_404(User,pk=pk)
    if request.method == 'POST':
        user.delete()
        messages.warning(request,"🗑️ User deleted successfully.")
        return redirect('user')
    context ={
        'user':user,
        'cancel':reverse('user')
    }
    return render(request,'dashboards/confirm_delete.html',context)

templates/dashboards/add_category.html
{% extends 'base.html' %}

{% block content %}

{% load crispy_forms_tags %}
<div class="row">
    <!-- Left side bar -->
    {% include 'dashboards/sidebar.html' %}

    <!-- Right side content -->
    <div class="col-md-9">
        {% if perms.blogs.add_categogy %}
        <h2>Add New Category</h2>
        <form action="" method="POST" style="width: 500px;">
            {% csrf_token %}
            {{ form | crispy }}
            <button type="submit" class="btn btn-warning">Submit</button>
        </form>
        <br>
        {% else %}
        <h5>You do not permission to add Category</h5>
        {% endif %}
    </div>
</div>

{% endblock %}

templates/dashboards/add_post.html
{% extends 'base.html' %}

{% block content %}

{% load crispy_forms_tags %}
<div class="row">
    <!-- Left side bar -->
    {% include 'dashboards/sidebar.html' %}

    <!-- Right side content -->
    <div class="col-md-9">
        {% if perms.blogs.add_blog %}
        <h2>Add New Posts</h2>
        <form action="{% url 'add_post' %}" method="POST" enctype="multipart/form-data">
            {{ form.media }}
            {% csrf_token %}
            {{ form | crispy }}
            <button type="submit" class="btn btn-warning">Submit</button>
        </form>
        <br>
        {% else %}
        <h5>You do not have permission add post</h5>
        {% endif %}
    </div>
</div>

{% endblock %}

templates/dashboards/add_user.html
{% extends 'base.html' %}

{% block content %}

{% load crispy_forms_tags %}
<div class="row">
    <!-- Left side bar -->
    {% include 'dashboards/sidebar.html' %}

    <!-- Right side content -->
    <div class="col-md-9">
    {% if perms.auth.add_user %}
        <h2>Add New User</h2>
        <form action="{% url 'add_user' %}" method="POST">
            {% csrf_token %}
            {{ form | crispy }}
            <button type="submit" class="btn btn-warning">Submit</button>
        </form>
        <br>
    {% else %}
    <h3>You don not have permission to add User</h3>
    {% endif %}
    </div>
</div>

{% endblock %}

templates/dashboards/categories.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
    <!-- Left side bar -->
    {% include 'dashboards/sidebar.html' %}

    <!-- Right side content -->
    <div class="col-md-9">
    {% if perms.blogs.view_category %}
    <h3>All Categories</h3>
    <a href="{% url 'add_category' %}" class="btn btn-dark text-light float-end mb-2" >Add New</a>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">S.No</th>
                <th scope="col">Category Name</th>
                <th scope="col">Created At</th>
                <th scope="col">Updated At</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for cat in categories %}
            <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td><a href="{% url 'post_by_category' cat.id  %}">{{cat.category_name}}</a></td>
            <td>{{cat.create_at}}</td>
            <td>{{cat.updated_at}}</td>
            <td>
                <a href="{% url 'edit_category' cat.id  %}"><i class="fa fa-edit text-success"></i></a>
                &nbsp;
                <a href="{% url 'delete_category' cat.id %}"><i class="fa fa-trash text-danger"></i></a>
            </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <h5>You do not have permission to view categogy</h5>
    {% endif %}
    </div>
</div>

{% endblock %}

templates/dashboards/confirm_delete.html
{% extends 'base.html' %}

{% block title %}Confirm Delete{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="card shadow-sm">
        <div class="card-body text-center">

            <h4 class="text-danger mb-3">
                ⚠️ Confirm Delete
            </h4>

            <p class="mb-4">
                Are you sure you want to delete
                <strong>{{ object_name }}</strong>?
                <br>
                This action cannot be undone.
            </p>

            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">
                    Yes, Delete
                </button>

                <a href="{{ cancel }}" class="btn btn-secondary ms-2">
                    Cancel
                </a>
            </form>

        </div>
    </div>
</div>
{% endblock %}

templates/dashboards/dashboards.html
{% extends 'base.html' %}

{% block content %}

{% if perms.blogs.add_category and perms.blogs.change_category and perms.blogs.add_blog and perms.blogs.change_blog %}
<div class="row">
    <!-- Left side bar -->
    {% include 'dashboards/sidebar.html' %}
    
    <!-- Right side content -->
    <div class="col-md-9">
        <div class="row">
            <div class="col">
                <div class="card border-default mb-3">
                    <div class="card-header text-center text-uppercase font-weight-bold">All Categories</div>
                    <div class="card-body text-dark">
                        <h5 class="card-title text-center">{{category_count}}</h5>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card border-default mb-3">
                    <div class="card-header text-center text-uppercase font-weight-bold">All Posts</div>
                    <div class="card-body text-dark">
                        <h5 class="card-title text-center">{{blogs_count}}</h5>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
{% else %}
<h5>You do not have permission to view dashboard</h5>
{% endif %}

{% endblock %}

templates/dashboards/edit_category.html
{% extends 'base.html' %}

{% block content %}

{% load crispy_forms_tags %}
<div class="row">
    <!-- Left side bar -->
    {% include 'dashboards/sidebar.html' %}

    <!-- Right side content -->
    <div class="col-md-9">
        {% if perms.blogs.change_categogy %}
        <h2>Edit Category</h2>
        <form action="{% url 'edit_category' category.id %}" method="POST" style="width: 500px;">
            {% csrf_token %}
            {{ form | crispy }}
            <button type="submit" class="btn btn-warning">Submit</button>
        </form>
        <br>
        {% else %}
        <h5>You do not have permission to edit the category</h5>
        {% endif %}
    </div>
</div>

{% endblock %}

templates/dashboards/edit_post.html
{% extends 'base.html' %}

{% block content %}

{% load crispy_forms_tags %}
<div class="row">
    <!-- Left side bar -->
    {% include 'dashboards/sidebar.html' %}

    <!-- Right side content -->
    <div class="col-md-9">
        {% if perms.blogs.change_blog %}
        <h2>Edit Post</h2>
        <form action="{% url 'edit_post' post.id %}" method="POST" style="width: 500px;">
            {% csrf_token %}
            {{ form | crispy }}
            <button type="submit" class="btn btn-warning">Submit</button>
        </form>
        <br>
        {% else %}
        <h5>You do not have permission to edit the post</h5>
        {% endif %}
    </div>
</div>

{% endblock %}

templates/dashboards/edit_user.html
{% extends 'base.html' %}

{% block content %}

{% load crispy_forms_tags %}
<div class="row">
    <!-- Left side bar -->
    {% include 'dashboards/sidebar.html' %}

    <!-- Right side content -->
    <div class="col-md-9">
        {% if perms.auth.change_user %}
        <h2>Edit User</h2>
        <form action="{% url 'edit_user' user.id %}" method="POST" style="width: 500px;">
            {% csrf_token %}
            {{ form | crispy }}
            <button type="submit" class="btn btn-warning">Submit</button>
        </form>
        <br>
        {% else %}
        <h5>You do not permmision to edit the user</h5>
        {% endif %}
    </div>
</div>

{% endblock %}

templates/dashboards/posts.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
    <!-- Left side bar -->
    {% include 'dashboards/sidebar.html' %}

    <!-- Right side content -->
    <div class="col-md-9">
    {% if perms.blogs.view_blog %}
    <h3>All Posts</h3>
    <a href="{% url 'add_post' %}" class="btn btn-dark text-light float-end mb-2">Add New</a>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">S.No</th>
                <th scope="col">Title</th>
                <th scope="col">Category</th>
                <th scope="col">Author</th>
                <th scope="col">Status</th>
                <th scope="col">Featured</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for post in posts %}
            <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td><a href="{% url 'blogs' post.slug %}">{{post.title}}</a></td>
            <td><a href="{% url 'post_by_category' post.category_id %}">{{post.category}}</a></td>
            <td>{{post.author}}</td>
            <td>{{post.status}}</td>
            <td>{{post.is_featured}}</td>
            <td>
                <a href="{% url 'edit_post' post.id %}"><i class="fa fa-edit text-success"></i></a>
                &nbsp;
                <a href="{% url 'delete_post' post.id %}"><i class="fa fa-trash text-danger"></i></a>
            </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <h5>You do not have permission to view blogs</h5>
    {% endif %}
    </div>
</div>

{% endblock %}

templates/dashboards/sidebar.html
<div class="col-md-3">
        <div class="nav flex-column nav-pills bg-light" aria-orientation="vertical">
            <a href="{% url 'dashboards' %}" class="nav-link text-dark {% if  '/dashboards/' == request.path  %} bg-warning {% endif %} ">Dashboard</a>
            {% if perms.auth.view_user %}
            <a href="{% url 'user' %}" class="nav-link text-dark {% if '/users/' in request.path %} bg-warning {% endif %} ">Users</a>
            {% endif %}
            <a href="{% url 'categories' %}" class="nav-link text-dark {% if '/categories/' in request.path %} bg-warning {% endif %} ">Categories</a>
            <a href="{% url 'posts' %}" class="nav-link text-dark {% if '/posts/' in request.path %} bg-warning {% endif %} ">Posts</a>
            <a href="{%url 'logout' %}" class="nav-link text-dark ">Logout</a>
        </div>
</div>

templates/dashboards/users.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
    <!-- Left side bar -->
    {% include 'dashboards/sidebar.html' %}

    <!-- Right side content -->
    <div class="col-md-9">
    {% if perms.auth.view_user %}
    <h3>All Users</h3>
    <a href="{% url 'add_user' %}" class="btn btn-dark text-light float-right mb-2">Add New</a>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">S.No</th>
                <th scope="col">User Name</th>
                <th scope="col">Full Name</th>
                <th scope="col">Email Address</th>
                <th scope="col">Status</th>
                <th scope="col">Featured</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for user in  users %}
            <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td><a href="">{{user.username}}</a></td>
            <td>{{user.first_name}} {{user.last_name}}</td>
            <td>{{user.email}}</td>
            <td>{% if user.is_active %} <i class="fa fa-check text-success"></i> {% else %} <i class="fa fa-times text-danger"></i> {% endif %}</td>
            <td>{% if user.is_staff %} <i class="fa fa-check text-success"></i> {% else %} <i class="fa fa-times text-danger"></i> {% endif %}</td>
            <td>
                <a href="{% url 'edit_user' user.id %}"><i class="fa fa-edit text-success"></i></a>
                &nbsp;
                <a href="{% url 'delete_user' user.id %}"><i class="fa fa-trash text-danger"></i></a>
            </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <h3>You do not have permission to View this page</h3>
    {% endif %}
    </div>
</div>

{% endblock %}